apiVersion: cache.azure.upbound.io/v1beta1
kind: Redis
metadata:
  name: my-redis-cache
spec:
  forProvider:
    resourceGroupName: aksproject
    location: canadacentral
    sku:
      name: your-sku-name
      family: your-sku-family
      capacity: your-sku-capacity
  providerConfigRef:
    name: azure-provider
  writeConnectionSecretToRef:
    name: redis-connection-details
    namespace: default
