apiVersion: cache.azure.upbound.io/v1beta1
kind: Redis
metadata:
  name: my-redis-cache
spec:
  forProvider:
    resourceGroupName: aksproject
    location: canadacentral
    sku:
      name: Standard
      family: C
      capacity: 1
  providerConfigRef:
    name: azure-provider
  writeConnectionSecretToRef:
    name: redis-connection-details
    namespace: default
