apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-backup
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: backup-image:latest
              env:
                - name: MONGO_URI
                  value: "mongodb://mongo:27017"
          restartPolicy: OnFailure
