apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>
    <source>
      @type tail
      path /var/log/user-service.log
      pos_file /var/log/fluentd.pos
      tag "user_service.login"
      <parse>
        @type regexp
        expression /^(?<time>[^\s]+ [^\s]+) (?<log_level>\w+): (?<message>.*)$/
        time_format "%Y-%m-%dT%H:%M:%S.%L%z"
        keep_time_key true
        types log_level:string, message:string
      </parse>
    </source>

    <filter user_service.login>
      @type parser
      key_name message
      format /Login attempt: (?<user>\w+)|User found: (?<user>\w+)|Password match: (?<match>true|false)|Invalid password for user: (?<user>\w+)/
      reserve_data true
    </filter>

    <match user_service.login>
      @type elasticsearch
      host elasticsearch.default.svc.cluster.local  # Adjust this if using a different namespace or service name
      port 9200
      logstash_format true
      logstash_prefix user_service
      include_tag_key true
      type_name _doc
    </match>
