apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: default
data:
  proxy-connect-timeout: "30"
  proxy-read-timeout: "30"
  proxy-send-timeout: "30"
  client-body-buffer-size: "10m"
  enable-vts-status: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: default
data:
  9000: "default/tcp-service:9000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: default
data:
  10000: "default/udp-service:10000"
