# Use the official MongoDB image
FROM mongo:latest

# Set environment variables for MongoDB
ENV MONGO_INITDB_ROOT_USERNAME admin
ENV MONGO_INITDB_ROOT_PASSWORD 1234

# Update apt and install MongoDB tools
RUN apt-get update \
    && apt-get install -y wget gnupg curl \
    && wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | apt-key add - \
    && echo "deb [arch=amd64,arm64] http://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list \
    && apt-get update \
    && apt-get install -y mongodb-mongosh \
    && rm -rf /var/lib/apt/lists/*

# Start MongoDB in the background, perform initialization, then shut it down
RUN mongod --fork --logpath /var/log/mongodb.log --dbpath /data/db --bind_ip localhost \
    && mongosh --eval "db = db.getSiblingDB('admin'); db.createUser({user: 'admin', pwd: '1234', roles: [{role: 'dbOwner', db: 'userService'}, {role: 'dbOwner', db: 'todoService'}]});" \
    && mongosh --eval "db = db.getSiblingDB('userService'); db.createCollection('someInitialCollection');" \
    && mongosh --eval "db = db.getSiblingDB('todoService'); db.createCollection('someInitialCollection');" \
    && mongod --shutdown

# Expose the MongoDB port
EXPOSE 27017

# Default command to run MongoDB server
CMD ["mongod"]
