version: '3.3'
services:
  notification-service:
    volumes:
      - ./Notification-service:/usr/src/app
      - /usr/src/app/node_modules
  user-service:
    volumes:
      - ./user-service:/usr/src/app
      - /usr/src/app/node_modules
  todo-service:
    volumes:
      - ./ToDo-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
