version: '3.8'  # Ensures compatibility with newer Docker features

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/custom-entrypoint.sh:/docker-entrypoint.d/custom-entrypoint.sh
    depends_on:
      - user-service
      - todo-service
      - notification-service
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/userService
    depends_on:
      - mongo
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  todo-service:
    build:
      context: ./todo-service
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoService
    depends_on:
      - mongo
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    depends_on:
      - user-service  # Assuming notifications might depend on user data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
