apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
type: Opaque
data:
  STORAGE_ACCOUNT: c2FtYW5kZXJhYmF5bmVoMQ==
  STORAGE_KEY: bnFON0hzVy9SRWpRRHJrdkFSYkd4SVRaM3dnanhOb1hnakNuRWJEa1BVYTF2OTRMMVZQRE5HRUdLWm56empjMXhaS1B6VDVjM2g0QytBU3Q3VFFwZGc9PQ==
  RESTIC_PASSWORD: c2FtYW5kZXJydXN0aWNwYXNzd29yZA==
