apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ include "todo.name" . | quote }}
    helm.sh/chart: {{ include "todo.chart" . | quote }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>
    <source>
      @type tail
      path /var/log/user-service.log
      pos_file /var/log/fluentd.pos
      tag "user_service.login"
      <parse>
        @type regexp
        expression /^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z) (?<log_level>\w+): (?<message>.*)$/
        time_format "%Y-%m-%dT%H:%M:%S.%LZ"
        keep_time_key true
      </parse>
    </source>

    <filter user_service.login>
      @type parser
      key_name message
      reserve_data true
      <parse>
        @type regexp
        expression /Login attempt: (?<user>\w+)|User found: (?<user>\w+)|Password match: (?<match>true|false)|Invalid password for user: (?<user>\w+)/
      </parse>
    </filter>

    <match user_service.login>
      @type elasticsearch
      host elasticsearch.default.svc.cluster.local  # Adjust this if using a different namespace or service name
      port 9200
      logstash_format true
      logstash_prefix "user_service"
      include_tag_key true
      type_name "_doc"
    </match>
