apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-backup
spec:
  schedule: "0 3 * * *"  # Runs at 3:00 AM every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: restic/restic:latest
            volumeMounts:
            - name: backup-storage
              mountPath: /backup  # Mount point for Restic repository
            env:
            - name: RESTIC_REPOSITORY
              value: "/backup"  # Use the mounted path in the PVC
            - name: AZURE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: STORAGE_ACCOUNT
            - name: AZURE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: STORAGE_KEY
            - name: RESTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: RESTIC_PASSWORD
            - name: AZURE_CONTAINER_NAME
              value: "mybackupcontainer"
            command: ["/bin/sh", "-c"]
            args:
              - |
                restic backup /backup && \
                restic -r azure:${AZURE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_CONTAINER_NAME} backup /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc-helm  # Using the PVC created
          restartPolicy: OnFailure


# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: data-backup
# spec:
#   schedule: "0 3 * * *"  # Runs at 3:00 AM every day
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: backup
#             image: restic/restic:latest
#             volumeMounts:
#             - name: backup-storage
#               mountPath: /backup  # Mount point for Restic repository
#             env:
#             - name: RESTIC_REPOSITORY
#               value: "/backup"  # Use the mounted path in the PVC
#           volumes:
#           - name: backup-storage
#             persistentVolumeClaim:
#               claimName: backup-pvc  # Using the PVC created
#           restartPolicy: OnFailure





