apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  labels:
    app: todo-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name: todo-service
          image: "{{ .Values.image.repository }}/todo-service:{{ .Values.image.tagTodoService }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URI
              value: "{{ .Values.env.TODO_SERVICE_MONGO_URI }}"
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
