apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  labels:
    app: todo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-service-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-service-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: todo-service-config
                  key: REDIS_PASSWORD
        - name: todo-service
          image: "{{ .Values.image.repository }}/todo-service:{{ .Values.image.tagTodoService }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URI
              value: "{{ .Values.env.TODO_SERVICE_MONGO_URI }}"
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
        - name: redis-sidecar
          image: redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-service-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-service-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: todo-service-config
                  key: REDIS_PASSWORD
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config



########################################

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: todo-service
#   labels:
#     app: todo-service
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: todo-service
#   template:
#     metadata:
#       labels:
#         app: todo-service
#     spec:
#       containers:
#         - name: todo-service
#           image: "{{ .Values.image.repository }}/todo-service:{{ .Values.image.tagTodoService }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - containerPort: 3003
#           env:
#             - name: MONGO_URI
#               value: "{{ .Values.env.TODO_SERVICE_MONGO_URI }}"
#             - name: JWT_SECRET
#               value: "{{ .Values.env.JWT_SECRET }}"
#           resources:
#             requests:
#               memory: "256Mi"
#               cpu: "100m"
#             limits:
#               memory: "512Mi"
#               cpu: "200m"



