{{- if .Values.autoscaling.userService.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "todo.fullname" . }}-user-service
  labels:
    {{- include "todo.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "todo.fullname" . }}-user-service
  minReplicas: {{ .Values.autoscaling.userService.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.userService.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.userService.targetCPUUtilizationPercentage }}
{{- end }}

{{- if .Values.autoscaling.todoService.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "todo.fullname" . }}-todo-service
  labels:
    {{- include "todo.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "todo.fullname" . }}-todo-service
  minReplicas: {{ .Values.autoscaling.todoService.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.todoService.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.todoService.targetCPUUtilizationPercentage }}
{{- end }}

{{- if .Values.autoscaling.notificationService.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "todo.fullname" . }}-notification-service
  labels:
    {{- include "todo.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "todo.fullname" . }}-notification-service
  minReplicas: {{ .Values.autoscaling.notificationService.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.notificationService.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.notificationService.targetCPUUtilizationPercentage }}
{{- end }}
