{{- if .Values.kibana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: kibana
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: SERVER_BASEPATH
              value: "/kibana"
            - name: SERVER_REWRITEBASEPATH
              value: "true"
          resources:
            requests:
              memory: "{{ .Values.kibana.resources.requests.memory }}"
              cpu: "{{ .Values.kibana.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.kibana.resources.limits.memory }}"
              cpu: "{{ .Values.kibana.resources.limits.cpu }}"
          volumeMounts:
            - name: kibana-storage
              mountPath: /usr/share/kibana/data
      volumes:
        - name: kibana-storage
          persistentVolumeClaim:
            claimName: kibana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
{{- end }}
