---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: "prom/prometheus:latest"
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus/'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--web.external-url=%(protocol)s://%(domain)s/prometheus/'
            - '--web.route-prefix=/prometheus'
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-storage
          emptyDir: {}
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-monitoring-config
data:
  nginx.conf: |
    events {}

    http {
      upstream grafana {
        server grafana.default.svc.cluster.local:3000;
      }

      upstream kibana {
        server kibana.default.svc.cluster.local:5601;
      }

      upstream prometheus {
        server prometheus.default.svc.cluster.local:9090;
      }

      server {
        listen 80;

        location /grafana/ {
          proxy_pass http://grafana/;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Cookie $http_cookie;
          proxy_set_header Authorization "";
          proxy_redirect off;
          sub_filter '"/' '"/grafana/';
          sub_filter_once off;
        }

        location /kibana/ {
          proxy_pass http://kibana/;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Cookie $http_cookie;
          proxy_set_header Authorization "";
          proxy_redirect off;
          sub_filter '"/' '"/kibana/';
          sub_filter_once off;
        }

        location /prometheus {
          return 301 /prometheus/;
        }

        location /prometheus/ {
          proxy_pass http://prometheus/;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Cookie $http_cookie;
          proxy_set_header Authorization "";
          proxy_redirect off;
          sub_filter '"/' '"/prometheus/';
          sub_filter_once off;
        }
      }
    }
