apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-monitoring-config
data:
  nginx.conf: |
    events {}

    http {
        upstream grafana {
            server grafana.default.svc.cluster.local:3000;
        }

        upstream kibana {
            server kibana.default.svc.cluster.local:5601;
        }

        upstream prometheus {
            server prometheus.default.svc.cluster.local:9090;
        }

        server {
            listen 80;

            location /grafana/ {
                proxy_pass http://grafana/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Cookie $http_cookie;
                proxy_set_header Authorization "";
                rewrite ^/grafana(/.*)$ $1 break;
            }

            location /kibana/ {
                proxy_pass http://kibana/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Cookie $http_cookie;
                proxy_set_header Authorization "";
                rewrite ^/kibana(/.*)$ $1 break;
            }

            location /prometheus/ {
                proxy_pass http://prometheus/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Cookie $http_cookie;
                proxy_set_header Authorization "";
                rewrite ^/prometheus(/.*)$ $1 break;
            }
        }
    }
