# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-monitoring
# spec:
#   selector:
#     app: nginx-monitoring
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: LoadBalancer
