{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          resources:
            requests:
              memory: "{{ .Values.prometheus.resources.requests.memory }}"
              cpu: "{{ .Values.prometheus.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.prometheus.resources.limits.memory }}"
              cpu: "{{ .Values.prometheus.resources.limits.cpu }}"
          ports:
            - containerPort: {{ .Values.prometheus.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.port }}
  selector:
    app: prometheus
{{- end }}
